version: '3.8'

services:
  api:
    build: .
    container_name: japan-travel-assistant-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - travel-assistant-network

  # Uncommenting this section will add Ollama as a service
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   networks:
  #     - travel-assistant-network

networks:
  travel-assistant-network:
    driver: bridge

# Uncomment if using Ollama service
# volumes:
#   ollama_data: 